
spring.datasource.url=jdbc:postgresql://ep-calm-morning-ahgq9rc7-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fONxn6Y4tBzI
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=32K/CHVAUcL2yV8pmUMiyjq7newe07oIc+YRmQtqhxZmhA4wm8ZrJqWYxLTqr7IXORRf/8qYiFMZ2+e4cTMeXw==
jwt.expiration-ms=86400000

server.port=8080
ai.service.url=http://localhost:8000

file.upload-dir=./uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

youtube.api.key=AIzaSyDtrna8I41p_9XcmW3abksou5KeWuTNkn8



